name:                nixtools
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jgertm/nixtools#readme
license:             BSD3
author:              Tim Jäger
maintainer:          jger.tm@gmail.com
copyright:           2018 Tim Jäger
category:            Web
extra-source-files:
- README.md

default-extensions:
  - ApplicativeDo
  - RecordWildCards
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - ScopedTypeVariables
  
ghc-options:
  - -fllvm
  - -threaded
  - -W

dependencies:
  - base >= 4.7 && < 5
  - filepath
  - filemanip
  - mono-traversable
  - optparse-applicative
  - process
  - universum

executables:
  nixtools-rebuild:
    source-dirs:      src
    main:             Rebuild.hs
